### ISSUE TITLE
Ideas Facet Roadmap

### ISSUE THREAD

**Issue by marclitchfield** [marclitchfield/mind#2]
Upcoming features for the Ideas Facet:

### Idea navigation, creation, editing, and deletion

* [x] Show root ideas
* [x] Submit root idea
* [x] Show child ideas
* [x] Show child type
* [x] Navigate to child
* [x] Navigate to root
* [x] Submit type
* [x] Show links to parent ideas for the selected idea
* [x] Edit body
* [x] Edit idea type (update predicates to parents and from parents to idea)
* [x] Delete idea - warn about orphans
* [x] Show grandchild indicators

### Sidebar search, recent ideas

* [ ] Idea Search - Sidebar on desktop
* [ ] Show recently added ideas in sidebar
* [ ] Show recently viewed ideas in sidebar

### More features
* [ ] Option to expand to show additional generations of ideas. 
* [ ] Show/Edit Confidence
* [ ] Option to sort by create date, descending
* [ ] Option to sort by confidence, descending
* [ ] Delete links to parents, warn about orphaning if last parent is deleted
* [ ] Link with additional parents from recently added or viewed ideas
* [ ] Move an idea to a new parent

### Mind connections

* [ ] Register connection to remote mind through mind api
* [ ] Show recently created ideas from connected minds in sidebar
* [ ] Show ideas from selected connected mind
* [ ] Link and import connected idea with selected local idea
* [ ] Show recently added ideas from connected minds in sidebar
* [ ] Disconnect from another mind. Ideas not imported will no longer be accessible
* [ ] Register a public identity through mind api
* [ ] Show public identity of idea creator
* [ ] Control which local ideas are exposed to connected minds

### General usability
* [x] Keyboard shortcuts for create and edit
* [ ] Keyboard navigation
* [ ] UI transitions
* [ ] Loading spinner
* [ ] Error messages
